name: Build USB-Monitor (Windows & macOS)

on:
  push:
    branches: ["main", "master"]
    tags: ["v*", "release-*", "*.*.*"]
  pull_request:
    branches: ["main", "master"]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-windows:
    name: Windows Build (.exe)
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build (PyInstaller)
        run: |
          python -m PyInstaller --noconfirm --onedir --windowed --name "USB-Monitor" src/main.py

      - name: Archive artifact (zip)
        shell: pwsh
        run: |
          Compress-Archive -Path "dist/USB-Monitor" -DestinationPath "USB-Monitor-Windows.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: USB-Monitor-Windows
          path: USB-Monitor-Windows.zip

  build-macos:
    name: macOS Build (.app)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build (PyInstaller)
        run: |
          python -m PyInstaller --noconfirm --onedir --windowed --name "USB-Monitor" src/main.py

      - name: Zip .app bundle
        run: |
          cd dist
          ditto -c -k --sequesterRsrc --keepParent "USB-Monitor.app" "../USB-Monitor-macOS.zip"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: USB-Monitor-macOS
          path: USB-Monitor-macOS.zip

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: [build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download Windows artifact
        uses: actions/download-artifact@v4
        with:
          name: USB-Monitor-Windows
          path: artifacts

      - name: Download macOS artifact
        uses: actions/download-artifact@v4
        with:
          name: USB-Monitor-macOS
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            artifacts/USB-Monitor-Windows.zip
            artifacts/USB-Monitor-macOS.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


